name: bts

networks:
  bts-discovery: {}

services:

  postgres:
    container_name: bts-postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
    networks:
      - bts-discovery

  grafana:
    container_name: bts-grafana
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${GF_PROVISIONING_DIRECTORY}:/etc/grafana/provisioning
    networks:
      - bts-discovery
