{
 "title": "HUAWEI",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "VERSION",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "rawSql": "SELECT * FROM huawei_version" }
   ]
  },
  {
   "title": "CARD",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "rawSql": "SELECT * FROM huawei_card" }
   ]
  },
  {
   "title": "MDA",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "rawSql": "SELECT * FROM huawei_mda" }
   ]
  },
  {
   "title": "TRANSCEIVER",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT * FROM huawei_transceiver"
    }
   ]
  }
 ]
}