{
 "title": "NOKIA",
 "description": "NOKIA SROS dashboards",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Chassis",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "rawSql": "SELECT * FROM nokia_chassis" }
   ]
  },
  {
   "title": "VERSION",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "rawSql": "SELECT * FROM nokia_version" }
   ]
  },
  {
   "title": "CARD",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "rawSql": "SELECT * FROM nokia_card" }
   ]
  },
  {
   "title": "MDA",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT * FROM nokia_mda LIMIT 50 "
    }
   ]
  },
  {
   "title": "TRANSCEIVER",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT * FROM nokia_transceiver"
    }
   ]
  }
 ]
}